set -g mouse on
set -g history-limit 10000
set -g renumber-windows on
set -g set-clipboard on

set -g default-terminal "tmux-256color"
set -ga terminal-features ",xterm-256color:RGB"

setw -g mode-keys vi
set -g status-keys vi

unbind C-b
set -g prefix C-a
bind C-a send-prefix

bind r source-file ~/.tmux.conf \; display-message "reloaded ~/.tmux.conf"
bind \\ split-window -h
bind - split-window -v
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

set -g @plugin 'rose-pine/tmux'
set -g @rose_pine_variant 'moon'
set -g @plugin 'tmux-plugins/tpm'

run '~/.tmux/plugins/tpm/tpm'
