backend = "fastresize"
color_space = "lch"
palette = "dark16"

[templates]
kitty = { template = "kitty.conf", target = "~/.config/kitty/colors.conf" }
waybar = { template = "waybar.css", target = "~/.config/waybar/colors.css" }
hyprland = { template = "hyprland.conf", target = "~/.config/hypr/config/colors.conf" }
rofi = { template = "rofi.rasi", target = "~/.config/rofi/colors.rasi" }
dunstrc = { template = "dunstrc", target = "~/.config/dunst/dunstrc" }