alias mkrepo-secrets='repo_secrets_init'
alias opencode='with_repo_secrets opencode'
alias chromium-wayland='XDG_CURRENT_DESKTOP=sway chromium --enable-features=UseOzonePlatform,WebRTCPipeWireCapturer --ozone-platform=wayland'
alias webex-kitty='${DOTFILES_ROOT:?}/scripts/distro/arch/labwc-run kitty'
alias webex-firefox='${DOTFILES_ROOT:?}/scripts/distro/arch/labwc-run env MOZ_ENABLE_WAYLAND=1 firefox --no-remote -P webex'
alias webex-chromium-x11='env XDG_SESSION_TYPE=x11 XDG_CURRENT_DESKTOP=sway chromium --user-data-dir="$HOME/.config/chromium-webex-x11" --ozone-platform=x11 --disable-features=WebRTCPipeWireCapturer'
alias kitty-xwayland='kitty -o linux_display_server=x11'
alias fm='yazi'
alias nfs-mount='sudo mount -t nfs'
alias nfs-umount='sudo umount'
