unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

bind \\ split-window -h
bind - split-window -v
unbind '"'
unbind %

bind r source-file ~/.tmux.conf; display-message "Config reloaded $TMUX_PROGRAM"

bind C-c new-session
bind C-f command-prompt -p find-session 'switch-client -t %%'

bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R

bind > swap-pane -D
bind < swap-pane -U

bind -r C-h previous-window
bind -r C-l next-window
bind Tab last-window

set -g history-limit 100000
set -g default-terminal screen-256color

set -s escape-time 10  # faster command sequence

setw -g mode-keys vi

set -g base-index 1
setw -g pane-base-index 1

set -g set-titles off

set -g monitor-activity on
set -g visual-activity off

set -g @plugin 'tmux-plugins/'
set -g @plugin 'tmux-plugins/sensible'

set -g @plugin 'dracula/tmux'

set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

run '~/.tmux/plugins/tpm/tpm'

set -g @continuum-restore on

set -g @dracula-plugins 'cpu-usage gpu-usage ssh-session weather time'
set -g @dracula-show-powerline true

set -g @dracula-show-timezone false
set -g @dracula-military-time true

set -g @dracula-show-fahrenheit true
