unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

set -s escape-time 10
set -sg repeat-time 600
set -s focus-events on

set -g history-limit 5000

set -g base-index 1
setw -g pane-base-index 1

setw -g automatic-rename on
set -g renumber-windows on

set -g set-titles on

set -g display-panes-time 800
set -g display-time 1000

set -g status-interval 10

set -g monitor-activity on
set -g visual-activity off

bind - split-window -v
bind \\ split-window -h

bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R

bind > swap-pane -D
bind < swap-pane -U

bind -r H resize-pane -L 2
bind -r J resize-pane -D 2
bind -r K resize-pane -U 2
bind -r L resize-pane -R 2

unbind n
unbind p
bind -r C-h previous-window
bind -r C-l next-window
bind Tab last-window

bind-key r source-file ~/.tmux.conf \; display-message 'Reloaded ~/.tmux.conf'

if-shell 'test -n "$SSH_CLIENT"' \
    'source-file ~/.tmux.remote.conf'

bind -T root F12 set prefix None \; set key-table off \; set status-left ' OFF ' \; if -F '#{pane_in_mode}' 'send-keys -X cancel' \; refresh-client -S

bind -T off F12 set -u prefix \; set -u key-table \; set status-left ''\; refresh-client -S

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

run '~/.tmux/plugins/tpm/tpm'
