unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

bind \\ split-window -h
bind - split-window -v
unbind '"'
unbind %

bind r source-file ~/.tmux.conf; display-message "Config reloaded"

bind C-c new-window -a

set -g history-limit 100000

setw -g mode-keys vi
